### ISSUE TITLE
how to use the api?

### ISSUE THREAD

**Issue by zimingyy** [lzhangbv/eva#1]
Hello, I had some problems when trying to use the eva algorithm. I have used the API correctly as described in the readme and paper to try to train some models on my own code, but when calling the kfac class, an error will be reported:

Traceback (most recent call last):
   File "ddp_eva.py", line 218, in <module>
     main()
   File "ddp_eva.py", line 135, in main
     preconditioner = eva(model)
   File "/ming01/exp1/kfac/eva.py", line 56, in __init__
     self._register_module_hooks(model)
   File "/ming01/exp1/kfac/eva.py", line 117, in _register_module_hooks
     if backend.comm.rank() == 0:
AttributeError: 'NoneType' object has no attribute 'rank'

How to solve this?
Or can you provide a more understandable and easy-to-use use case to facilitate novices to use your algorithm?
I think this is a pretty great job and hope to get your reply, thank you!

**Comment by lzhangbv** [comment]
The backend uses either Horovod or PyTorch-DDP to support distributed training, and it should be initialized in the beginning as shown below: 
https://github.com/lzhangbv/eva/blob/master/examples/pytorch_cifar10_resnet.py#L141
